### PR TITLE
Adding support for the User object containing an access token.

### PR DESCRIPTION
**Pull request by Trudeaucj**
In order to support Account Linking in the Alexa skill I've added the user to the route call. This pulls the user object out of the session data.

### CODE REVIEW

**Comment by Trudeaucj** [comment]
Might actually be better to put this when the new skill is returned instead.

**Comment by cameronhunter** [comment]
Do you think it's worth just passing the `session` object to the constructor?

**Comment by Trudeaucj** [comment]
Definitely, just started using more parts of session.

**Comment by cameronhunter** [comment]
The `attributes` are already in the session, I think we can just pass `session` to the constructor instead of both.

**Comment by Trudeaucj** [comment]
Ah right, thanks.

**Comment by cameronhunter** [comment]
Looks good. In the future I might move this to the router like you had originally – it's always felt strange to me that the attributes were on the instance instead of just passed to the routed function.

I'll merge this and release it as a new major version. Thanks!

**Comment by cameronhunter** [comment]
Published at v6.0.0

**Comment by Trudeaucj** [comment]
Awesome, thanks :) I was thinking that same but seeing as I'll need the user token each call it made sense to have it on the instance.

**Pull request merged**
